#ifndef __BSP_ADVANCEDTIM_INPUTCAPTURE_MEAPWM_H__
#define __BSP_ADVANCEDTIM_INPUTCAPTURE_MEAPWM_H__

#include "stm32f10x.h"

typedef struct
{
	__IO uint16_t IC2Value;
	__IO uint16_t IC1Value;
}ICxCountValueStruct;

  
#define TIM_1

//* ----------------   PWM信号 周期和占空比的计算--------------- */
// ARR ：自动重装载寄存器的值
// CLK_cnt：计数器的时钟，等于 Fck_int / (psc+1) = 72M/(psc+1)
// PWM 信号的周期 T = ARR * (1/CLK_cnt) = ARR*(PSC+1) / 72M

// 输入捕获能捕获到的最小的频率为 72M/{ (ARR+1)*(PSC+1) }
#define ADVANCEDTIM_PRESCALER		 72-1  //psc
#define ADVANCEDTIM_PERIOD       1000-1  //ARR

#define ADVANCEDTIM_GPIO_CLK_FUNC    RCC_APB2PeriphClockCmd
#define ADVANCEDTIM_GPIO_CLK   			 RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB | RCC_APB2Periph_GPIOC


#define ADVANCEDTIM_CLK_FUNC  			 RCC_APB2PeriphClockCmd

#define ADVANCEDTIM_CHANNELx 				TIM_Channel_1

/* TIM1、TIM8输出引脚 */
/* 因为只有TI1FP1和TI2FP2连到了从模式控制器，所以PWM输入模式只能使用TIMx_CH1/TIMx_CH2信号。 */
#if defined(TIM_1)
//TIM1,TIM1只有CHANNEL1的两个互补引脚可以外接杜邦线
#define ADVANCEDTIMx   							TIM1
#define ADVANCEDTIM_CLK  						RCC_APB2Periph_TIM1

#define ADVANCEDTIM_CCx_IRQ         TIM1_CC_IRQn   
#define ADVANCEDTIM_CCx_IRQHANDLER  TIM1_CC_IRQHandler 

//#define ADVANCEDTIM_CHANNEL1
#define ADVANCEDTIM_CHANNEL1_PORT   	GPIOA
#define ADVANCEDTIM_CHANNEL1_PIN    	GPIO_Pin_8
//#define ADVANCEDTIM_CHANNEL1_PORT			GPIOE
//#define ADVANCEDTIM_CHANNEL1_PIN			GPIO_Pin_9
//#define ADVANCEDTIM_CHANNEL1_N
#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_13
//#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOA
//#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_7
//#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOE
//#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_8

//#define ADVANCEDTIM_CHANNEL2
#define ADVANCEDTIM_CHANNEL2_PORT			GPIOA
#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_9
//#define ADVANCEDTIM_CHANNEL2_PORT			GPIOE
//#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_11
//#define ADVANCEDTIM_CHANNEL2_N
#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_14
//#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
//#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_0
//#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOE
//#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_10

//TIM18
#else

#define ADVANCEDTIMx   							TIM8
#define ADVANCEDTIM_CLK  						RCC_APB2Periph_TIM8

#define ADVANCEDTIM_CCx_IRQ         TIM8_CC_IRQn   
#define ADVANCEDTIM_CCx_IRQHANDLER  TIM8_CC_IRQHandler 

//#define ADVANCEDTIM_CHANNEL1
#define ADVANCEDTIM_CHANNEL1_PORT			GPIOC
#define ADVANCEDTIM_CHANNEL1_PIN			GPIO_Pin_6

//#define ADVANCEDTIM_CHANNEL1_N
#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOA
#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_7

//#define ADVANCEDTIM_CHANNEL2
#define ADVANCEDTIM_CHANNEL2_PORT			GPIOC
#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_7

//#define ADVANCEDTIM_CHANNEL2_N
#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_0

#endif

void AdvancedTim_Init(void);

#endif /* __BSP_ADVANCEDTIM_INPUTCAPTURE_MEAPWM_H__ */

