#ifndef __BSP_GENERALTIM_OUTPUT_PWM_H__
#define __BSP_GENERALTIM_OUTPUT_PWM_H__

#include "stm32f10x.h"


#define GENERALTIM_GPIO_CLK_FUNC	RCC_APB2PeriphClockCmd

#define GENERALTIM_GPIO_CLK       (RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB |\
																	RCC_APB2Periph_GPIOC | RCC_APB2Periph_GPIOD)
																			
#define GENERALTIM_CLK_FUNC				RCC_APB1PeriphClockCmd  

//* ----------------   PWM信号 周期和占空比的计算--------------- */
// ARR ：自动重装载寄存器的值
// CLK_cnt：计数器的时钟，等于 Fck_int / (psc+1) = 72M/(psc+1)
// PWM 信号的周期 T = ARR * (1/CLK_cnt) = ARR*(PSC+1) / 72M
// 占空比P=CCR/(ARR+1)

// 输出PWM的频率为 72M/{ (ARR+1)*(PSC+1) }
#define GENERALTIM_PRESCALER		72-1  //psc
#define GENERALTIM_PERIOD       10-1  //ARR

//channel1~channel4的占空比(CCR)
#define GENERALTIM_CHANNEL1_PULSE 	5
#define GENERALTIM_CHANNEL2_PULSE 	4
#define GENERALTIM_CHANNEL3_PULSE 	3
#define GENERALTIM_CHANNEL4_PULSE 	2


#define TIMx_3

//TIM2
#ifdef TIMx_2
#define GENERALTIMx     TIM2
#define GENERALTIM_CLK  					RCC_APB1Periph_TIM2
#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_0
#define GENERALTIM_CHANNEL1_PORT  GPIOA
//#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_15
//#define GENERALTIM_CHANNEL1_PORT  GPIOA

#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_1
#define GENERALTIM_CHANNEL2_PORT  GPIOA
//#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_3
//#define GENERALTIM_CHANNEL1_PORT  GPIOB

#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_2
#define GENERALTIM_CHANNEL3_PORT  GPIOA
//#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_10
//#define GENERALTIM_CHANNEL3_PORT  GPIOB

#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_3
#define GENERALTIM_CHANNEL4_PORT  GPIOA
//#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_11
//#define GENERALTIM_CHANNEL4_PORT  GPIOB

//TIM3
#elif defined(TIMx_3)
#define GENERALTIMx     TIM3
#define GENERALTIM_CLK  					RCC_APB1Periph_TIM3
#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_6
#define GENERALTIM_CHANNEL1_PORT  GPIOA
//#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_6
//#define GENERALTIM_CHANNEL1_PORT  GPIOC
//#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_4
//#define GENERALTIM_CHANNEL1_PORT  GPIOB

#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_7
#define GENERALTIM_CHANNEL2_PORT  GPIOA
//#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_7
//#define GENERALTIM_CHANNEL2_PORT  GPIOC
//#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_5
//#define GENERALTIM_CHANNEL2_PORT  GPIOB

#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_0
#define GENERALTIM_CHANNEL3_PORT  GPIOB
//#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_8
//#define GENERALTIM_CHANNEL3_PORT  GPIOC

#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_1
#define GENERALTIM_CHANNEL4_PORT  GPIOB
//#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_9
//#define GENERALTIM_CHANNEL4_PORT  GPIOC

//TIM4
#elif defined(TIMx_4)
#define GENERALTIMx     TIM4
#define GENERALTIM_CLK  					RCC_APB1Periph_TIM4
#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_6
#define GENERALTIM_CHANNEL1_PORT  GPIOB
//#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_12
//#define GENERALTIM_CHANNEL1_PORT  GPIOD

#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_7
#define GENERALTIM_CHANNEL2_PORT  GPIOB
//#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_13
//#define GENERALTIM_CHANNEL2_PORT  GPIOD

#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_8
#define GENERALTIM_CHANNEL3_PORT  GPIOB
//#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_14
//#define GENERALTIM_CHANNEL3_PORT  GPIOD

#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_9
#define GENERALTIM_CHANNEL4_PORT  GPIOB
//#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_15
//#define GENERALTIM_CHANNEL4_PORT  GPIOD

//TIM5
#elif defined(TIMx_5)
#define GENERALTIMx     TIM5
#define GENERALTIM_CLK  					RCC_APB1Periph_TIM5
#define GENERALTIM_CHANNEL1_PIN   GPIO_Pin_0
#define GENERALTIM_CHANNEL1_PORT  GPIOA

#define GENERALTIM_CHANNEL2_PIN   GPIO_Pin_1
#define GENERALTIM_CHANNEL2_PORT  GPIOA

#define GENERALTIM_CHANNEL3_PIN   GPIO_Pin_2
#define GENERALTIM_CHANNEL3_PORT  GPIOA

#define GENERALTIM_CHANNEL4_PIN   GPIO_Pin_3
#define GENERALTIM_CHANNEL4_PORT  GPIOA
#endif

void GeneralTim_Init(void);

#endif /* __BSP_GENERALTIM_OUTPUT_PWM_H__ */
