#ifndef __BSP_ADVANCEDTIM_COMPLEMENTARYOUTPUT_H__
#define __BSP_ADVANCEDTIM_COMPLEMENTARYOUTPUT_H__

#include "stm32f10x.h"
  
#define TIM_1

//* ----------------   PWM信号 周期和占空比的计算--------------- */
// ARR ：自动重装载寄存器的值
// CLK_cnt：计数器的时钟，等于 Fck_int / (psc+1) = 72M/(psc+1)
// PWM 信号的周期 T = ARR * (1/CLK_cnt) = ARR*(PSC+1) / 72M
// 占空比P=CCR/(ARR+1)

#define ADVANCEDTIM_PRESCALER		 9-1  //psc
#define ADVANCEDTIM_PERIOD       10-1  //ARR

#define ADVANCEDTIM_GPIO_CLK_FUNC    RCC_APB2PeriphClockCmd
#define ADVANCEDTIM_GPIO_CLK   			 RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB | RCC_APB2Periph_GPIOC


#define ADVANCEDTIM_CLK_FUNC  			 RCC_APB2PeriphClockCmd

/* TIM1、TIM8互补输出引脚 */
#if defined(TIM_1)
//TIM1,TIM1只有CHANNEL1的两个互补引脚可以外接杜邦线
#define ADVANCEDTIMx   TIM1
#define ADVANCEDTIM_CLK  RCC_APB2Periph_TIM1
#define ADVANCEDTIM_PULSE    5  //占空比

//#define ADVANCEDTIM_CHANNEL1
#define ADVANCEDTIM_CHANNEL1_PORT   	GPIOA
#define ADVANCEDTIM_CHANNEL1_PIN    	GPIO_Pin_8
//#define ADVANCEDTIM_CHANNEL1_PORT			GPIOE
//#define ADVANCEDTIM_CHANNEL1_PIN			GPIO_Pin_9
//#define ADVANCEDTIM_CHANNEL1_N
#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_13
//#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOA
//#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_7
//#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOE
//#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_8

//#define ADVANCEDTIM_CHANNEL2
#define ADVANCEDTIM_CHANNEL2_PORT			GPIOA
#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_9
//#define ADVANCEDTIM_CHANNEL2_PORT			GPIOE
//#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_11
//#define ADVANCEDTIM_CHANNEL2_N
#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_14
//#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
//#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_0
//#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOE
//#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_10

//#define ADVANCEDTIM_CHANNEL3
#define ADVANCEDTIM_CHANNEL3_PORT			GPIOA
#define ADVANCEDTIM_CHANNEL3_PIN			GPIO_Pin_10
//#define ADVANCEDTIM_CHANNEL3_PORT			GPIOE
//#define ADVANCEDTIM_CHANNEL3_PIN			GPIO_Pin_13
//#define ADVANCEDTIM_CHANNEL3_N
#define ADVANCEDTIM_CHANNEL3_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL3_N_PIN		GPIO_Pin_15
//#define ADVANCEDTIM_CHANNEL3_N_PORT		GPIOB
//#define ADVANCEDTIM_CHANNEL3_N_PIN		GPIO_Pin_1
//#define ADVANCEDTIM_CHANNEL3_N_PORT		GPIOE
//#define ADVANCEDTIM_CHANNEL3_N_PIN		GPIO_Pin_12

//TIM1 BKIN刹车GPIO
#define ADVANCEDTIM_BKIN_PORT   GPIOB
#define ADVANCEDTIM_BKIN_PIN   	GPIO_Pin_12
//#define ADVANCEDTIM_BKIN_PORT   GPIOA
//#define ADVANCEDTIM_BKIN_PIN   	GPIO_Pin_6
//#define ADVANCEDTIM_BKIN_PORT   GPIOE
//#define ADVANCEDTIM_BKIN_PIN   	GPIO_Pin_15

//TIM18
#else

#define ADVANCEDTIMx   TIM8
#define ADVANCEDTIM_CLK  RCC_APB2Periph_TIM8
//#define ADVANCEDTIM_CHANNEL1
#define ADVANCEDTIM_CHANNEL1_PORT			GPIOC
#define ADVANCEDTIM_CHANNEL1_PIN			GPIO_Pin_6

//#define ADVANCEDTIM_CHANNEL1_N
#define ADVANCEDTIM_CHANNEL1_N_PORT		GPIOA
#define ADVANCEDTIM_CHANNEL1_N_PIN		GPIO_Pin_7

//#define ADVANCEDTIM_CHANNEL2
#define ADVANCEDTIM_CHANNEL2_PORT			GPIOC
#define ADVANCEDTIM_CHANNEL2_PIN			GPIO_Pin_7

//#define ADVANCEDTIM_CHANNEL2_N
#define ADVANCEDTIM_CHANNEL2_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL2_N_PIN		GPIO_Pin_0

//#define ADVANCEDTIM_CHANNEL3
#define ADVANCEDTIM_CHANNEL3_PORT			GPIOC
#define ADVANCEDTIM_CHANNEL3_PIN			GPIO_Pin_8

//#define ADVANCEDTIM_CHANNEL3_N
#define ADVANCEDTIM_CHANNEL3_N_PORT		GPIOB
#define ADVANCEDTIM_CHANNEL3_N_PIN		GPIO_Pin_1

//TIM8 BKIN刹车GPIO
#define ADVANCEDTIM_BKIN_PORT   GPIOA
#define ADVANCEDTIM_BKIN_PIN   	GPIO_Pin_6

#endif

void AdvancedTim_Init(void);

#endif /* __BSP_ADVANCEDTIM_COMPLEMENTARYOUTPUT_H__ */
